#!/usr/bin/env python3
"""単独提出ファイルを生成し、問題形式の愚直比較と任意の公式生成器を実行する。
公式リポジトリは --official-root で指定する（このスクリプトはネット接続しない）。
"""
import argparse
import json
import platform
import random
import subprocess
import tempfile
import time
import tomllib
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
MOD = 998244353


def run(cmd, **kw):
    return subprocess.run([str(x) for x in cmd], check=True, **kw)


def random_case(seed):
    rng = random.Random(seed)
    n, q = rng.randrange(1, 65), 300
    keys = rng.sample(range(10**9 + 1), n + q)
    a = [(keys[i], rng.randrange(1, MOD), rng.randrange(MOD)) for i in range(n)]
    lines = [f"{n} {q}", *(f"{p} {x} {y}" for p, x, y in a)]
    expected = []
    for step in range(q):
        t = rng.randrange(4)
        if t == 0:
            i = rng.randrange(n)
            v = (keys[n + step], rng.randrange(1, MOD), rng.randrange(MOD))
            lines.append(f"0 {i} {v[0]} {v[1]} {v[2]}")
            a[i] = v
        else:
            l, r = sorted(rng.sample(range(n + 1), 2))
            if t == 1:
                x = rng.randrange(MOD)
                lines.append(f"1 {l} {r} {x}")
                for _, b, c in a[l:r]:
                    x = (b * x + c) % MOD
                expected.append(str(x))
            else:
                lines.append(f"{t} {l} {r}")
                a[l:r] = sorted(a[l:r], reverse=t == 3)
    return ("\n".join(lines) + "\n").encode(), ("\n".join(expected) + "\n").encode()


def hard_case(kind):
    rng = random.Random(123456)
    n = q = 100000
    keys = list(range(n))
    rng.shuffle(keys)
    lines = [f"{n} {q}", *(f"{k} {i % 997 + 1} {i % 991}" for i, k in enumerate(keys))]
    for step in range(q):
        if step % 17 == 16:
            l = rng.randrange(n)
            r = rng.randrange(l + 1, n + 1)
            lines.append(f"1 {l} {r} {step % MOD}")
        elif kind == "alternating_full":
            lines.append(f"{2 + step % 2} 0 {n}")
        elif kind == "shifted_windows":
            l = step % (n // 2)
            lines.append(f"{2 + step % 2} {l} {l + n // 2}")
        elif kind == "update_full_sort":
            if step % 2 == 0:
                lines.append(f"0 {rng.randrange(n)} {n + step} {step % 997 + 1} {step % 991}")
            else:
                lines.append(f"{2 + (step // 2) % 2} 0 {n}")
        elif kind == "fragment_then_merge":
            if step % 10000 < 9900:
                lines.append(f"0 {rng.randrange(n)} {n + step} {step % 997 + 1} {step % 991}")
            else:
                lines.append(f"{2 + step % 2} 0 {n}")
        else:
            raise AssertionError(kind)
    return ("\n".join(lines) + "\n").encode()


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--official-root", type=Path)
    parser.add_argument("--report", type=Path, default=ROOT / "tests/keyed_avl_results.json")
    args = parser.parse_args()
    tree = (ROOT / "src/SegmentTree/keyed_avl_tree.rs").read_text()
    seq = (ROOT / "src/SegmentTree/sortable_sequence.rs").read_text()
    seq = seq[seq.index("struct SortableBlock"):]
    example = (ROOT / "examples/point_set_range_sort_range_composite.rs").read_text()
    example = example[example.index("use std::io"):]
    submission = ROOT.parent / "librarychecker/submissions/point_set_range_sort_range_composite.rs"
    submission.write_text("// Generated by arcaki_library/tests/check_keyed_avl_tree.py\n#![allow(dead_code)]\n" + tree + "\n" + seq + "\n" + example)
    report = {"platform": platform.platform(), "random_seeds": 100, "official": [], "hard": [], "submission": str(submission)}
    with tempfile.TemporaryDirectory(prefix="keyed_avl_check_") as tmp:
        tmp = Path(tmp)
        binary = tmp / "main"
        run(["rustc", "--edition=2021", "-O", submission, "-o", binary])
        for seed in range(100):
            inp, expected = random_case(seed)
            actual = run([binary], input=inp, stdout=subprocess.PIPE, timeout=10).stdout
            if actual.split() != expected.split():
                failure = ROOT / "tests/keyed_avl_failure.in"
                failure.write_bytes(inp)
                raise AssertionError(f"seed={seed}; saved {failure}")
        print("100 deterministic random input/output cases: passed", flush=True)
        if args.official_root:
            upstream = args.official_root.resolve()
            problem = upstream / "data_structure/point_set_range_sort_range_composite"
            info = tomllib.loads((problem / "info.toml").read_text())
            (problem / "params.h").write_text("\n".join(f"#define {k} {v}LL" for k, v in info["params"].items()) + "\n")
            def compile_cpp(src, output):
                run(["c++", "-O2", "-std=c++17", "-I", upstream / "common", src, "-o", output])
            reference = tmp / "reference"
            verifier = tmp / "verifier"
            compile_cpp(problem / "sol/correct.cpp", reference)
            compile_cpp(problem / "verifier.cpp", verifier)
            for test in info["tests"]:
                name = test["name"]
                generator = tmp / Path(name).stem
                if name.endswith(".cpp"):
                    compile_cpp(problem / "gen" / name, generator)
                for seed in range(test["number"]):
                    inp = ((problem / "gen" / f"example_{seed:02}.in").read_bytes()
                           if name.endswith(".in") else run([generator, seed], stdout=subprocess.PIPE).stdout)
                    run([verifier], input=inp, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
                    expected = run([reference], input=inp, stdout=subprocess.PIPE, timeout=30).stdout
                    start = time.perf_counter()
                    actual = run([binary], input=inp, stdout=subprocess.PIPE, timeout=30).stdout
                    elapsed = time.perf_counter() - start
                    if actual.split() != expected.split():
                        failure = ROOT / "tests/keyed_avl_failure.in"
                        failure.write_bytes(inp)
                        raise AssertionError(f"{name}/{seed}: saved {failure}")
                    n, q = map(int, inp.split(b"\n", 1)[0].split())
                    report["official"].append({"name": name, "seed": seed, "n": n, "q": q, "seconds": elapsed, "result": "matched"})
                    print(f"{name}/{seed}: N={n}, Q={q}, {elapsed:.3f}s, matched", flush=True)
            for kind in ["alternating_full", "shifted_windows", "update_full_sort", "fragment_then_merge"]:
                inp = hard_case(kind)
                run([verifier], input=inp, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
                expected = run([reference], input=inp, stdout=subprocess.PIPE, timeout=30).stdout
                start = time.perf_counter()
                actual = run([binary], input=inp, stdout=subprocess.PIPE, timeout=30).stdout
                elapsed = time.perf_counter() - start
                if actual.split() != expected.split():
                    failure = ROOT / "tests/keyed_avl_failure.in"
                    failure.write_bytes(inp)
                    raise AssertionError(f"{kind}: saved {failure}")
                report["hard"].append({"name": kind, "n": 100000, "q": 100000, "seconds": elapsed, "result": "matched"})
                print(f"hard/{kind}: N=Q=100000, {elapsed:.3f}s, matched", flush=True)
    args.report.write_text(json.dumps(report, indent=2) + "\n")
    print(f"report: {args.report}")


if __name__ == "__main__":
    main()
